version: '3.7'

services:
  vue-mumtaz:
    image: node:18-alpine
    container_name: chisu-dashboard-ui
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5174:5173"
    command: sh -c "yarn && yarn dev-docker"
    networks:
      - winata-network
networks:
  winata-network:
    external: true
    driver: bridge
